sudo: required
language: cpp
compiler:
   - gcc

addons:
  apt:
    packages:
      - valgrind
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test
script:
   - mkdir build
   - cd build
   - cmake ..
   - make