sudo: required
dist: trusty
language: cpp
compiler:
   - gcc
   - clang
addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
         - llvm-toolchain-precise-3.6
      packages:
         - gcc-5
         - g++-5
         - clang-3.6
script:
   - mkdir build
   - cd build
   - cmake ../test/
   - make